FROM node:20.16.0

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

ARG TIMESTAMP
ARG PRODUCTS
ARG MAX_TIME
ARG DESTINATION_FOLDER

ENV TIMESTAMP=${TIMESTAMP}
ENV PRODUCTS=${PRODUCTS}
ENV MAX_TIME=${MAX_TIME}
ENV DESTINATION_FOLDER=${DESTINATION_FOLDER}

# Run the script
CMD ["node", "dist/index.mjs"]